ADA03/force-app/main/default/objects/Account/fields/Submit_Annual_Revenue_Date__c.field-meta.xml
<CustomField>
    <fullName>Submit_Annual_Revenue_Date__c</fullName>
    <label>Submit Annual Revenue Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

ADA03/force-app/main/default/objects/Opportunity/fields/Annual_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Annual_Revenue__c</fullName>
    <label>Annual Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ADA03/force-app/main/default/objects/Opportunity/fields/Submit_Annual_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Submit_Annual_Revenue__c</fullName>
    <label>Submit Annual Revenue</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

ADA03/force-app/main/default/classes/CreateAccountHandler.cls
public with sharing class CreateAccountHandler {
    
    public static void createOpportunitiesFromAccounts(List<Account> accounts){
        List<Opportunity> opps = new List<Opportunity>();
        for(Account a : accounts){
            Opportunity opp = new Opportunity();
            opp.Name = a.Name + ' Opportunity';
            opp.AccountId = a.Id;
            opp.StageName = 'Prospecting';
            opp.Annual_Revenue__c = a.AnnualRevenue;
            opp.Submit_Annual_Revenue__c = a.Submit_Annual_Revenue_Date__c;
            opp.CloseDate = System.Today().addMonths(1);
            opps.add(opp);
        }

        if(opps.size() > 0){
           insert opps;
        }
    }
}