ADA03/force-app/main/default/objects/Opportunity/fields/Annual_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Annual_Revenue__c</fullName>
    <label>Annual Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ADA03/force-app/main/default/objects/Opportunity/fields/Colour_Flag__c.field-meta.xml
<CustomField>
    <fullName>Colour_Flag__c</fullName>
    <label>Colour Flag</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ADA03/force-app/main/default/objects/Opportunity/fields/Submit_Annual_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Submit_Annual_Revenue__c</fullName>
    <label>Submit Annual Revenue</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

ADA03/force-app/main/default/classes/OpportunityRevenueTriggerHandler.cls
public with sharing class OpportunityRevenueTriggerHandler {

    public static void assignColourRevenue(List<Opportunity> opps){

        for(Opportunity opp : opps){
            if(opp.Submit_Annual_Revenue__c < Date.today()){
                if(opp.Annual_Revenue__c < 10000){
                    opp.Colour_Flag__c = 'RED';
                }else{
                    if(opp.Annual_Revenue__c < 30000){
                        opp.Colour_Flag__c = 'YELLOW';
                    }else{
                        opp.Colour_Flag__c = 'GREEN';
                        
                    }
                }
            }
        }
    }
}